### ISSUE TITLE
Cannot able to create the table when we using Enum Data type in  Entity class

### ISSUE THREAD

**Issue by Parameshwaran-DT** [yurimarx/iris-java-tools#1]
Hello,

I am unable to fix this issue (using an enum in the entity class; it's not creating the table). I have seen many references on websites, but all of them are using Quarkus versions below 3, and InterSystems jar version is 3.3.0. No one can use Quarkus version 3, and no one has published a suitable dialect for Quarkus 3. Could you please provide a solution or a dialect folder to help me solve this issue?

Thank you.

**Comment by yurimarx** [comment]
Can you send me here your class source code?

**Comment by Parameshwaran-DT** [comment]
Yeah Sure!

```
@Getter
@Setter
@Entity
@NoArgsConstructor
@Table(name = "COMMENTS")
public class CommentEntity {

  @Id private UUID id;

  @CreationTimestamp private LocalDateTime createdAt;
  @UpdateTimestamp private LocalDateTime updatedAt;

  private String body;

  @Enumerated(EnumType.STRING)
  @Column(name="purpose_type")
  private PurposeType purposeType;

  public enum PurposeType {
    CANCEL,
    ACTIVATE,
  }

  @ManyToOne
  @JoinColumn(name = "article_id", referencedColumnName = "id", nullable = false)
  private ArticleEntity article;

  @ManyToOne
  @JoinColumn(name = "author_id", referencedColumnName = "id", nullable = false)
  private UserEntity author;

}

```

For your reference, this is the error log

![oie_PFZCWA6YezGJ](https://github.com/yurimarx/iris-java-tools/assets/106385514/089fc478-66f7-40e3-9af1-aa1041a4514c)

**Comment by Parameshwaran-DT** [comment]
hello yurimarx,

is there any update?
We don't use CHECK constraint, by default Hibernate will generate this query. I don't know it has some issues in dialect file. It has become a mandatory requirement for us to use Enums in our application. I'm unsure why this functionality isn't achievable in Quarkus versions 3 and above. We previously achieved this in Quarkus version 2, and it worked seamlessly with other databases like MySQL and PostgreSQL. However, I'm puzzled as to why I can't annotate Enum types in the IRIS database.

Can you please tell us if is there any possible way to achieve it? 

Thanks in advance.

**Comment by yurimarx** [comment]
Fixed, please, change your dialect dependency for 1.1.1

**Comment by Parameshwaran-DT** [comment]
Thanks yurimarx Marx
Now, I was able to successfully connect to the database also create a table using Enum data type.
